bflad/tfproviderlint

.goreleaser.yml, CHANGELOG.md, README.md, cmd/tfproviderlintx/tfproviderlintx.go, helper/cmdflags/version.go, xpasses/checks.go
=> Add tfproviderlintx command and document custom lint tool implementation

CHANGELOG.md, passes/resourcedatagetok/resourcedatagetok.go
=> New Analyzer: resourcedatagetok: returns ResourceData.GetOk() calls for later passes

CHANGELOG.md, passes/resourcedataget/resourcedataget.go
=> New Analyzer: resourcedataget: returns ResourceData.Get() calls for later passes

CHANGELOG.md, passes/resourcedatagetchange/resourcedatagetchange.go
=> New Analyzer: resourcedatagetchange: returns ResourceData.GetChange() calls for later passes

LICENSE
Passes unlicensable check:
```console
$ unlicensable LICENSE
[{path:LICENSE cover:{Percent:100 Match:[{Name:MPL-2.0 Type:9 Percent:100 Start:0 End:16718 IsURL:false}]}}]
```
=> Add MPL-2.0 LICENSE file

CHANGELOG.md, README.md, go.mod, go.sum, passes/R009/R009.go, passes/R009/R009_test.go, passes/R009/README.md, passes/R009/testdata/src/a/main.go, passes/checks.go, vendor/github.com/bflad/gopaniccheck/LICENSE, vendor/github.com/bflad/gopaniccheck/passes/logpaniccallexpr/analyzer.go, vendor/github.com/bflad/gopaniccheck/passes/logpanicfcallexpr/analyzer.go, vendor/github.com/bflad/gopaniccheck/passes/logpaniclncallexpr/analyzer.go, vendor/github.com/bflad/gopaniccheck/passes/paniccallexpr/analyzer.go, vendor/modules.txt
=> New Check: R009: Avoid Go panic usage

CHANGELOG.md, README.md, passes/AT008/AT008.go, passes/AT008/AT008_test.go, passes/AT008/README.md, passes/AT008/testdata/src/a/main.go, passes/checks.go
=> New Check: AT008: check for acceptance test function declaration *testing.T parameter naming

.github/workflows/incoming.yaml, .github/workflows/release.yaml
Reference: https://github.com/bflad/tfproviderlint/pull/119/files#diff-37aff102a57d3d7b797f152915a6dc16
=> tests: Add dependency checking via go mod to incoming and release GitHub Actions

helper/terraformtype/terraform/package.go, helper/terraformtype/terraform/type_resourceprovider.go, helper/terraformtype/terraform/type_resourceprovider_test.go
=> helper/terraformtype/terraform: New package for working with github.com/hashicorp/terraform-plugin-sdk/terraform and ResourceProvider type

CHANGELOG.md, helper/astutils/expr.go, helper/astutils/fieldlist.go, helper/astutils/fieldlist_test.go, helper/terraformtype/helper/customdiff/funcs.go, helper/terraformtype/helper/customdiff/package.go, helper/terraformtype/helper/customdiff/type_resourceconditionfunc.go, helper/terraformtype/helper/customdiff/type_resourceconditionfunc_test.go, helper/terraformtype/helper/customdiff/type_valuechangeconditionfunc.go, helper/terraformtype/helper/customdiff/type_valuechangeconditionfunc_test.go, helper/terraformtype/helper/customdiff/type_valuechangevalidationfunc.go, helper/terraformtype/helper/customdiff/type_valuechangevalidationfunc_test.go, helper/terraformtype/helper/customdiff/type_valueconditionfunc.go, helper/terraformtype/helper/customdiff/type_valueconditionfunc_test.go, helper/terraformtype/helper/customdiff/type_valuevalidationfunc.go, helper/terraformtype/helper/customdiff/type_valuevalidationfunc_test.go, helper/terraformtype/helper/schema/type_resourcediff.go, helper/terraformtype/helper/schema/type_resourcediff_test.go, passes/helper/customdiff/resourceconditionfuncinfo/resourceconditionfuncinfo.go, passes/helper/customdiff/resourceconditionfuncinfo/resourceconditionfuncinfo_test.go, passes/helper/customdiff/valuechangeconditionfuncinfo/valuechangeconditionfuncinfo.go, passes/helper/customdiff/valuechangeconditionfuncinfo/valuechangeconditionfuncinfo_test.go, passes/helper/customdiff/valuechangevalidationfuncinfo/valuechangevalidationfuncinfo.go, passes/helper/customdiff/valuechangevalidationfuncinfo/valuechangevalidationfuncinfo_test.go, passes/helper/customdiff/valueconditionfuncinfo/valueconditionfuncinfo.go, passes/helper/customdiff/valueconditionfuncinfo/valueconditionfuncinfo_test.go, passes/helper/customdiff/valuevalidationfuncinfo/valuevalidationfuncinfo.go, passes/helper/customdiff/valuevalidationfuncinfo/valuevalidationfuncinfo_test.go
=> Add helper/terraformtype/helper/customdiff and passes/helper/customdiff for working with SDK customdiff package

CHANGELOG.md, helper/astutils/expr.go, helper/terraformtype/helper/schema/type_stateupgradefunc.go, helper/terraformtype/helper/schema/type_stateupgradefunc_test.go, passes/helper/schema/stateupgradefuncinfo/stateupgradefuncinfo.go, passes/helper/schema/stateupgradefuncinfo/stateupgradefuncinfo_test.go
=> Add helper/terraformtype/helper/schema and passes/helper/schema for working with StateUpgradeFunc

CHANGELOG.md, helper/terraformtype/helper/schema/type_customizedifffunc.go, helper/terraformtype/helper/schema/type_customizedifffunc_test.go, passes/helper/schema/customizedifffuncinfo/customizedifffuncinfo.go, passes/helper/schema/customizedifffuncinfo/customizedifffuncinfo_test.go
=> Add helper/terraformtype/helper/schema and passes/helper/schema for working with CustomizeDiffFunc

CHANGELOG.md, helper/terraformtype/helper/schema/type_provider.go, helper/terraformtype/helper/schema/type_provider_test.go
=> helper/terraformtype/helper/schema: Constants and functions for working with Provider type

CHANGELOG.md, helper/analysisutils/analyzers.go, helper/analysisutils/runners.go, helper/astutils/package.go, passes/helper/schema/providertypeassertexpr/providertypeassertexpr.go, passes/helper/schema/providertypeassertexpr/providertypeassertexpr_test.go, passes/terraform/resourceproviderselectorexpr/resourceproviderselectorexpr.go, passes/terraform/resourceproviderselectorexpr/resourceproviderselectorexpr_test.go
Also verified in separate implementation.
=> Various enhancements for SDK v2 upgrade handling

helper/terraformtype/helper/schema/testdata/type_resource/resource.go, helper/terraformtype/helper/schema/type_resource.go, helper/terraformtype/helper/schema/type_resource_test.go
=> helper/terraformtype/helper/schema: Prevent panics in NewResourceInfo

helper/terraformtype/helper/schema/type_customizedifffunc.go, helper/terraformtype/helper/schema/type_customizedifffunc_test.go
Reference: https://github.com/bflad/tfproviderlint/issues/178
=> helper/terraformtype/helper/schema: Ensure CustomizeDiffFunc handling supports Terraform Plugin SDK v2

CHANGELOG.md, passes/helper/validation/stringinslicecallexpr/stringinslicecallexpr.go, passes/helper/validation/stringinslicecallexpr/stringinslicecallexpr_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14601
=> passes/helper/validation: Pass for collecting `validation.StringInSlice()` calls

CHANGELOG.md, README.md, passes/R018/R018.go, passes/R018/R018_test.go, passes/R018/README.md, passes/R018/testdata/src/a/alias.go, passes/R018/testdata/src/a/comment_ignore.go, passes/R018/testdata/src/a/main.go, passes/R018/testdata/src/a/outside_package.go, passes/R018/testdata/src/a/time/main.go, passes/checks.go, passes/stdlib/timesleepcallexpr/timesleepfcallexpr.go, passes/stdlib/timesleepcallexpr/timesleepfcallexpr_test.go
=> New Analyzer and Check: timesleepcallexpr and R018

helper/astutils/package.go
=> helper/astutils: Prevent (*types.Info).ObjectOf() type assertion panics

passes/AT001/testdata/src/a/comment_ignore.go, passes/commentignore/ignore.go
=> passes/commentignore: Support multiple comma separated keys and extra // comments

CHANGELOG.md, README.md, passes/V011/README.md, passes/V011/V011.go, passes/V011/V011_test.go, passes/V011/testdata/src/a/main.go, passes/V012/README.md, passes/V012/V012.go, passes/V012/V012_test.go, passes/V012/testdata/src/a/main.go, passes/V013/README.md, passes/V013/V013.go, passes/V013/V013_test.go, passes/V013/testdata/src/a/main.go, passes/V014/README.md, passes/V014/V014.go, passes/V014/V014_test.go, passes/V014/testdata/src/a/main.go, passes/checks.go
=> New Checks: Additional Custom SchemaValidateFunc Checks for SDK Validation Functions

CHANGELOG.md, go.mod, go.sum, helper/terraformtype/helper/schema/type_resource.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new.go, vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go, vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go, vendor/github.com/hashicorp/terraform-plugin-sdk/v2/meta/meta.go, vendor/modules.txt, xpasses/XR006/XR006.go, xpasses/XR006/testdata/src/a/main_v2.go
Also support `helper/schema.Resource` `*WithoutTimeout` fields in `terraformtype` and `xpasses/XR006`
=> Update Terraform Plugin SDK v1 and v2

CHANGELOG.md, README.md, helper/analysisutils/analyzers.go, helper/analysisutils/runners.go, helper/analysisutils/stdlib_analyzers.go, helper/analysisutils/stdlib_runners.go, passes/stdlib/osexeccommandcallexpr/osexeccommandcallexpr.go, passes/stdlib/osexeccommandcallexpr/osexeccommandcallexpr_test.go, passes/stdlib/osexeccommandcontextcallexpr/osexeccommandcontextcallexpr.go, passes/stdlib/osexeccommandcontextcallexpr/osexeccommandcontextcallexpr_test.go, passes/stdlib/osexeccommandcontextselectorexpr/osexeccommandcontextselectorexpr.go, passes/stdlib/osexeccommandcontextselectorexpr/osexeccommandcontextselectorexpr_test.go, passes/stdlib/osexeccommandselectorexpr/osexeccommandselectorexpr.go, passes/stdlib/osexeccommandselectorexpr/osexeccommandselectorexpr_test.go, xpasses/XR007/README.md, xpasses/XR007/XR007.go, xpasses/XR007/XR007_test.go, xpasses/XR007/testdata/src/a/alias.go, xpasses/XR007/testdata/src/a/alias.go.golden, xpasses/XR007/testdata/src/a/main.go, xpasses/XR007/testdata/src/a/main.go.golden, xpasses/XR008/README.md, xpasses/XR008/XR008.go, xpasses/XR008/XR008_test.go, xpasses/XR008/testdata/src/a/alias.go, xpasses/XR008/testdata/src/a/alias.go.golden, xpasses/XR008/testdata/src/a/main.go, xpasses/XR008/testdata/src/a/main.go.golden, xpasses/checks.go
=> New Checks: XR007 and XR008: Check for os/exec.Command and os/exec.CommandContext Usage

Dockerfile
Reference: https://github.com/bflad/tfproviderlint/pull/299
=> Update Docker image to golang:1.21-bookworm
